package ti4.discord.interactions.slashcommands;

import java.util.Collection;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import java.util.stream.Stream;
import lombok.experimental.UtilityClass;
import ti4.discord.interactions.slashcommands.admin.AdminCommand;
import ti4.discord.interactions.slashcommands.agenda.AgendaCommand;
import ti4.discord.interactions.slashcommands.async.AsyncCommand;
import ti4.discord.interactions.slashcommands.bothelper.BothelperCommand;
import ti4.discord.interactions.slashcommands.breakthrough.BreakthroughCommand;
import ti4.discord.interactions.slashcommands.button.GenericButtonCommand;
import ti4.discord.interactions.slashcommands.cardsac.ACCardsCommand;
import ti4.discord.interactions.slashcommands.cardspn.PNCardsCommand;
import ti4.discord.interactions.slashcommands.cardsso.SOCardsCommand;
import ti4.discord.interactions.slashcommands.combat.CombatCommand;
import ti4.discord.interactions.slashcommands.custom.CustomCommand;
import ti4.discord.interactions.slashcommands.developer.DeveloperCommand;
import ti4.discord.interactions.slashcommands.draft.DraftCommand;
import ti4.discord.interactions.slashcommands.ds.DiscordantStarsCommand;
import ti4.discord.interactions.slashcommands.event.EventCommand;
import ti4.discord.interactions.slashcommands.explore.ExploreCommand;
import ti4.discord.interactions.slashcommands.fow.FOWCommand;
import ti4.discord.interactions.slashcommands.franken.FrankenCommand;
import ti4.discord.interactions.slashcommands.game.GameCommand;
import ti4.discord.interactions.slashcommands.help.HelpCommand;
import ti4.discord.interactions.slashcommands.installation.InstallationCommand;
import ti4.discord.interactions.slashcommands.leaders.LeaderCommand;
import ti4.discord.interactions.slashcommands.map.MapCommand;
import ti4.discord.interactions.slashcommands.milty.MiltyCommand;
import ti4.discord.interactions.slashcommands.omega_phase.OmegaPhaseCommand;
import ti4.discord.interactions.slashcommands.planet.PlanetCommand;
import ti4.discord.interactions.slashcommands.player.PlayerCommand;
import ti4.discord.interactions.slashcommands.relic.RelicCommand;
import ti4.discord.interactions.slashcommands.rules.RulesCommand;
import ti4.discord.interactions.slashcommands.search.FindCommand;
import ti4.discord.interactions.slashcommands.search.SearchCommand;
import ti4.discord.interactions.slashcommands.search.SearchCommand2;
import ti4.discord.interactions.slashcommands.special.Special2Command;
import ti4.discord.interactions.slashcommands.special.SpecialCommand;
import ti4.discord.interactions.slashcommands.spin.SpinCommand;
import ti4.discord.interactions.slashcommands.statistics.StatisticsCommand;
import ti4.discord.interactions.slashcommands.statistics.StatisticsCommand2;
import ti4.discord.interactions.slashcommands.status.StatusCommand;
import ti4.discord.interactions.slashcommands.tech.TechCommand;
import ti4.discord.interactions.slashcommands.tf.TwilightFallCommand;
import ti4.discord.interactions.slashcommands.tigl.TiglCommand;
import ti4.discord.interactions.slashcommands.tokens.AddCCCommand;
import ti4.discord.interactions.slashcommands.tokens.AddFrontierTokensCommand;
import ti4.discord.interactions.slashcommands.tokens.AddTokenCommand;
import ti4.discord.interactions.slashcommands.tokens.RemoveAllCC;
import ti4.discord.interactions.slashcommands.tokens.RemoveCCCommand;
import ti4.discord.interactions.slashcommands.tokens.RemoveTokenCommand;
import ti4.discord.interactions.slashcommands.transaction.TransactionCommand;
import ti4.discord.interactions.slashcommands.uncategorized.AllInfoCommand;
import ti4.discord.interactions.slashcommands.uncategorized.CardsInfoCommand;
import ti4.discord.interactions.slashcommands.uncategorized.SelectionBoxDemoCommand;
import ti4.discord.interactions.slashcommands.uncategorized.ShowDistancesCommand;
import ti4.discord.interactions.slashcommands.uncategorized.ShowGameCommand;
import ti4.discord.interactions.slashcommands.units.AddUnitDamage;
import ti4.discord.interactions.slashcommands.units.AddUnits;
import ti4.discord.interactions.slashcommands.units.CaptureCommand;
import ti4.discord.interactions.slashcommands.units.ModifyUnitsButtons;
import ti4.discord.interactions.slashcommands.units.MoveUnits;
import ti4.discord.interactions.slashcommands.units.RemoveAllUnitDamage;
import ti4.discord.interactions.slashcommands.units.RemoveAllUnits;
import ti4.discord.interactions.slashcommands.units.RemoveUnitDamage;
import ti4.discord.interactions.slashcommands.units.RemoveUnits;
import ti4.discord.interactions.slashcommands.user.UserCommand;

@UtilityClass
public class SlashCommandManager {

    private static final Map<String, ParentCommand> commands = Stream.of(
                    new AddUnits(),
                    new RemoveUnits(),
                    new RemoveAllUnits(),
                    new AllInfoCommand(),
                    new CardsInfoCommand(),
                    new ShowGameCommand(),
                    new ShowDistancesCommand(),
                    new AddCCCommand(),
                    new RemoveCCCommand(),
                    new RemoveAllCC(),
                    new SearchCommand2(),
                    new FindCommand(),
                    new AddFrontierTokensCommand(),
                    new MoveUnits(),
                    new ModifyUnitsButtons(),
                    new RemoveTokenCommand(),
                    new AddTokenCommand(),
                    new AddUnitDamage(),
                    new RemoveUnitDamage(),
                    new RemoveAllUnitDamage(),
                    new TransactionCommand(),
                    new MapCommand(),
                    new HelpCommand(),
                    new SearchCommand(),
                    new ExploreCommand(),
                    new RelicCommand(),
                    new RulesCommand(),
                    new AdminCommand(),
                    new DeveloperCommand(),
                    new BothelperCommand(),
                    new PlayerCommand(),
                    new GameCommand(),
                    new ACCardsCommand(),
                    new PNCardsCommand(),
                    new SOCardsCommand(),
                    new StatusCommand(),
                    new AgendaCommand(),
                    new EventCommand(),
                    new SpecialCommand(),
                    new Special2Command(),
                    new LeaderCommand(),
                    new CombatCommand(),
                    new CustomCommand(),
                    new FOWCommand(),
                    new InstallationCommand(),
                    new MiltyCommand(),
                    new FrankenCommand(),
                    new CaptureCommand(),
                    new GenericButtonCommand(),
                    new DiscordantStarsCommand(),
                    new TwilightFallCommand(),
                    new StatisticsCommand(),
                    new StatisticsCommand2(),
                    new TechCommand(),
                    new BreakthroughCommand(),
                    new PlanetCommand(),
                    new SelectionBoxDemoCommand(),
                    new UserCommand(),
                    new TiglCommand(),
                    new AsyncCommand(),
                    new OmegaPhaseCommand(),
                    new DraftCommand(),
                    new SpinCommand())
            .collect(Collectors.toMap(ParentCommand::getName, command -> command));

    public static ParentCommand getCommand(String name) {
        return commands.get(name);
    }

    public static Collection<ParentCommand> getCommands() {
        return List.copyOf(commands.values());
    }
}
