creussalpha=creussalpha,token_creussalpha,ghostalpha
creussbeta=creussbeta,token_creussbeta,ghostbeta
creussgamma=creussgamma,token_creussgamma,ghostgamma
custodian=custodian,token_custodian
custodianvp=custodianvp,token_custodianvp
dmz_large=dmz_large,token_dmz_large
frontier=frontier,token_frontier
gamma=gamma,token_gamma
gravityrift=gravityrift,token_gravityrift,gravrift
ionalpha=ionalpha,token_ionalpha
ionbeta=ionbeta,token_ionbeta
mirage=mirage,token_mirage
avernus=avernus,token_avernus,token_avernus.png
brokenplanet1=brokenplanet1,token_brokenplanet1,token_brokenplanet1.png,ceres
brokenplanet2=brokenplanet2,token_brokenplanet2,token_brokenplanet2.png,tycho
brokenplanet3=brokenplanet3,token_brokenplanet3,token_brokenplanet3.png,eros
brokenplanet4=brokenplanet4,token_brokenplanet4,token_brokenplanet4.png,ganymede
brokenplanet5=brokenplanet5,token_brokenplanet5,token_brokenplanet5.png,medina
brokenplanet6=brokenplanet6,token_brokenplanet6,token_brokenplanet6.png,anderson
kairnexpedition=kairnexpedition,expedition
xytherismine=xytherismine,mine
thundersedge=thundersedge,token_thundersedge
sleeper=sleeper,token_sleeper
speaker=speaker,token_speaker
worlddestroyed=worlddestroyed,token_worlddestroyed
consulate=consulate,token_consulate
freesystems_raccoon=freesystems_raccoon,raccoon,coon
freepeoples=freepeoples
supernova=supernova,nova
nebula=nebula,gascloud
entropicscar=entropicscar,scar
asteroids=asteroids,rocks
