version: "3.9"

services:
  asyncti4-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: asyncti4-bot
    restart: unless-stopped
    command: ["${BOT_TOKEN}", "1479318931641733291", "901547041866526800"]
    environment:
      - DB_PATH=/app/data/
    volumes:
      - ./data:/app/data
      - ./data/games:/app/games
      - ./data/maps:/app/maps
      - ./data/storage:/app/storage
    ports:
      - "8271:8081"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
