server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: prometheus

spring:
  datasource:
    url: "${POSTGRES_JDBC_URL:jdbc:postgresql://localhost:5432/tibot}"
    username: "${POSTGRES_USER:tibot}"
    password: "${POSTGRES_PASSWORD:}"
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: ${POSTGRES_POOL_SIZE:10}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        jdbc:
          time_zone: UTC
          batch_size: 100
          order_inserts: true
          order_updates: true
          generate_statistics: false
    open-in-view: false
  web:
    error:
      include-stacktrace: never
      include-binding-errors: never
      include-message: always

ti4:
  deploy:
    lease-key: discord-bot
    lease-duration-seconds: 30
    heartbeat-interval-seconds: 1

combat-contest:
  is-dev: ${COMBAT_CONTEST_IS_DEV:false}
