package ti4.service.draft;

import net.dv8tion.jda.api.components.buttons.Button;

/**
 * @param choiceKey        A unique key for this choice, all lowercase alpha-numeric characters.
 *                         Used in commands.
 * @param button           The button to use to select this choice. Should have the right text and emoji already.
 *                         Should have an ID generated by the Draftable which will route it back to the Draftable.
 * @param formattedName    A nicely formatted name for this choice, suitable for display in messages.
 * @param unformattedName  A simple, unformatted name for this choice, suitable for unformatted displays.
 *                         For example, the slash-command autocompleter uses this.
 * @param identifyingEmoji An optional emoji which should uniquely identify this choice to players.
 *                         Used to produce very shorthand summaries of player choices.
 *                         Ex. "Titans of Ul" can use the faction symbol.
 *                         Ex. franken's "Terragenesis" doesn't have a unique emoji, since there are other faction abilities.
 */
public record DraftChoice(DraftableType type, String choiceKey, Button button, String formattedName,
                          String unformattedName, String identifyingEmoji) {
}
