package ti4.service.draft;

import lombok.Data;
import net.dv8tion.jda.api.components.buttons.Button;

@Data
public class DraftChoice {
    private final DraftableType type;
    /**
     * A unique key for this choice, all lowercase alpha-numeric characters.
     * Used in commands.
     */
    private final String choiceKey;
    /**
     * The button to use to select this choice. Should have the right text and emoji already.
     * Should have an ID generated by the Draftable which will route it back to the Draftable.
     */
    private final Button button;
    /**
     * A nicely formatted name for this choice, suitable for display in messages.
     */
    private final String formattedName;
    /**
     * A simple, unformatted name for this choice, suitable for unformatted displays.
     * For example, the slash-command autocompleter uses this.
     */
    private final String unformattedName;
    /**
     * An optional emoji which should uniquely identify this choice to players.
     * Used to produce very shorthand summaries of player choices.
     * Ex. "Titans of Ul" can use the faction symbol.
     * Ex. franken's "Terragenesis" doesn't have a unique emoji, since there are other faction abilities.
     */
    private final String identifyingEmoji;
}
