package ti4.message;

public enum GameMessageType {
    AGENDA_WHEN,
    AGENDA_AFTER,
    AGENDA_DEADLY_PLOT,
    AGENDA_CONFOUNDING_CONFUSING_LEGAL_TEXT,
    ACTION_CARD,
    TURN,
    BAG_DRAFT,
    STATUS_SCORING,
    STATUS_END
}
