package ti4.helpers;

import java.util.ArrayList;
import java.util.List;
import java.util.Collections;
import ti4.model.ColorModel;

public class ColourHelper {

    public static List<ColorModel> sortColours(String factionId, List<ColorModel> colours) {
        List<ColorModel> newcolours = new ArrayList<ColorModel>(colours);
        // sort by name for deterministic sorting
        newcolours.sort((c1, c2) -> c1.getAlias().compareTo(c2.getAlias()));
        // sort by colour
        newcolours.sort((c1, c2) -> colourValue(factionId, c2) - colourValue(factionId, c1));
        // for each "page" of colours, 
        for (int x = 0; x < newcolours.size(); x+=22) {
            Collections.shuffle(newcolours.subList(x, Math.min(x+22, newcolours.size())));
        }
        newcolours.sort((c1, c2) -> colourValue(factionId, c2) - colourValue(factionId, c1));
        return newcolours;
    }

    private static int colourValue(String factionId, ColorModel colour)
    {
        switch (factionId)
        {
            case "arborec":
                switch (colour.getAlias())
                {
                    case "lgy":
                    case "gry":
                    case "blk":
                        return 24;
                    case "splitlgy":
                    case "splitgry":
                    case "splitblk":
                    case "orca":
                        return 4;
                    case "red":
                    case "bld":
                        return 25;
                    case "splitred":
                    case "splitbld":
                        return 5;
                    case "org":
                        return 23;
                    case "splitorg":
                        return 3;
                    case "tan":
                    case "bwn":
                    case "chk":
                        return 33;
                    case "splittan":
                    case "splitbwn":
                    case "splitchk":
                        return 13;
                    case "spr":
                    case "ylw":
                    case "gld":
                    case "crm":
                        return 26;
                    case "splitspr":
                    case "splitylw":
                    case "splitgld":
                    case "splitcrm":
                        return 6;
                    case "lme":
                    case "grn":
                    case "tqs":
                    case "frs":
                    case "eme":
                        return 39;
                    case "splitlme":
                    case "splitgrn":
                    case "splittqs":
                    case "splitfrs":
                    case "spliteme":
                        return 19;
                    case "tea":
                    case "ptr":
                    case "eth":
                    case "blu":
                    case "nvy":
                        return 21;
                    case "splittea":
                    case "splitptr":
                    case "spliteth":
                    case "splitblu":
                    case "splitnvy":
                        return 1;
                    case "lvn":
                    case "ppl":
                    case "sns":
                        return 20;
                    case "splitlvn":
                    case "splitppl":
                    case "splitsns":
                        return 0;
                    case "rse":
                    case "pnk":
                        return 21;
                    case "splitrse":
                    case "splitpnk":
                        return 1;
                    case "rbw":
                        return 21;
                    case "splitrbw":
                        return 1;
            }
            case "ghost":
                switch (colour.getAlias())
                {
                    case "lgy":
                    case "gry":
                    case "blk":
                        return 27;
                    case "splitlgy":
                    case "splitgry":
                    case "splitblk":
                    case "orca":
                        return 7;
                    case "red":
                    case "bld":
                        return 22;
                    case "splitred":
                    case "splitbld":
                        return 2;
                    case "org":
                        return 20;
                    case "splitorg":
                        return 0;
                    case "tan":
                    case "bwn":
                    case "chk":
                        return 21;
                    case "splittan":
                    case "splitbwn":
                    case "splitchk":
                        return 1;
                    case "spr":
                    case "ylw":
                    case "gld":
                    case "crm":
                        return 21;
                    case "splitspr":
                    case "splitylw":
                    case "splitgld":
                    case "splitcrm":
                        return 1;
                    case "lme":
                    case "grn":
                    case "tqs":
                    case "frs":
                    case "eme":
                        return 21;
                    case "splitlme":
                    case "splitgrn":
                    case "splittqs":
                    case "splitfrs":
                    case "spliteme":
                        return 1;
                    case "tea":
                    case "ptr":
                    case "eth":
                    case "blu":
                    case "nvy":
                        return 40;
                    case "splittea":
                    case "splitptr":
                    case "spliteth":
                    case "splitblu":
                    case "splitnvy":
                        return 20;
                    case "lvn":
                    case "ppl":
                    case "sns":
                        return 27;
                    case "splitlvn":
                    case "splitppl":
                    case "splitsns":
                        return 7;
                    case "rse":
                    case "pnk":
                        return 24;
                    case "splitrse":
                    case "splitpnk":
                        return 4;
                    case "rbw":
                        return 33;
                    case "splitrbw":
                        return 3;
            }
            case "hacan":
                switch (colour.getAlias())
                {
                    case "lgy":
                    case "gry":
                    case "blk":
                        return 20;
                    case "splitlgy":
                    case "splitgry":
                    case "splitblk":
                    case "orca":
                        return 0;
                    case "red":
                    case "bld":
                        return 26;
                    case "splitred":
                    case "splitbld":
                        return 6;
                    case "org":
                        return 31;
                    case "splitorg":
                        return 11;
                    case "tan":
                    case "bwn":
                    case "chk":
                        return 30;
                    case "splittan":
                    case "splitbwn":
                    case "splitchk":
                        return 10;
                    case "spr":
                    case "ylw":
                    case "gld":
                    case "crm":
                        return 38;
                    case "splitspr":
                    case "splitylw":
                    case "splitgld":
                    case "splitcrm":
                        return 18;
                    case "lme":
                    case "grn":
                    case "tqs":
                    case "frs":
                    case "eme":
                        return 23;
                    case "splitlme":
                    case "splitgrn":
                    case "splittqs":
                    case "splitfrs":
                    case "spliteme":
                        return 3;
                    case "tea":
                    case "ptr":
                    case "eth":
                    case "blu":
                    case "nvy":
                        return 24;
                    case "splittea":
                    case "splitptr":
                    case "spliteth":
                    case "splitblu":
                    case "splitnvy":
                        return 4;
                    case "lvn":
                    case "ppl":
                    case "sns":
                        return 23;
                    case "splitlvn":
                    case "splitppl":
                    case "splitsns":
                        return 3;
                    case "rse":
                    case "pnk":
                        return 22;
                    case "splitrse":
                    case "splitpnk":
                        return 2;
                    case "rbw":
                        return 29;
                    case "splitrbw":
                        return 9;
            }
            case "jolnar":
                switch (colour.getAlias())
                {
                    case "lgy":
                    case "gry":
                    case "blk":
                        return 23;
                    case "splitlgy":
                    case "splitgry":
                    case "splitblk":
                    case "orca":
                        return 3;
                    case "red":
                    case "bld":
                        return 23;
                    case "splitred":
                    case "splitbld":
                        return 3;
                    case "org":
                        return 22;
                    case "splitorg":
                        return 2;
                    case "tan":
                    case "bwn":
                    case "chk":
                        return 21;
                    case "splittan":
                    case "splitbwn":
                    case "splitchk":
                        return 1;
                    case "spr":
                    case "ylw":
                    case "gld":
                    case "crm":
                        return 24;
                    case "splitspr":
                    case "splitylw":
                    case "splitgld":
                    case "splitcrm":
                        return 4;
                    case "lme":
                    case "grn":
                    case "tqs":
                    case "frs":
                    case "eme":
                        return 27;
                    case "splitlme":
                    case "splitgrn":
                    case "splittqs":
                    case "splitfrs":
                    case "spliteme":
                        return 7;
                    case "tea":
                    case "ptr":
                    case "eth":
                    case "blu":
                    case "nvy":
                        return 36;
                    case "splittea":
                    case "splitptr":
                    case "spliteth":
                    case "splitblu":
                    case "splitnvy":
                        return 16;
                    case "lvn":
                    case "ppl":
                    case "sns":
                        return 34;
                    case "splitlvn":
                    case "splitppl":
                    case "splitsns":
                        return 14;
                    case "rse":
                    case "pnk":
                        return 27;
                    case "splitrse":
                    case "splitpnk":
                        return 7;
                    case "rbw":
                        return 25;
                    case "splitrbw":
                        return 5;
            }
            case "l1z1x":
                switch (colour.getAlias())
                {
                    case "lgy":
                    case "gry":
                    case "blk":
                        return 34;
                    case "splitlgy":
                    case "splitgry":
                    case "splitblk":
                    case "orca":
                        return 14;
                    case "red":
                    case "bld":
                        return 34;
                    case "splitred":
                    case "splitbld":
                        return 14;
                    case "org":
                        return 23;
                    case "splitorg":
                        return 3;
                    case "tan":
                    case "bwn":
                    case "chk":
                        return 27;
                    case "splittan":
                    case "splitbwn":
                    case "splitchk":
                        return 7;
                    case "spr":
                    case "ylw":
                    case "gld":
                    case "crm":
                        return 25;
                    case "splitspr":
                    case "splitylw":
                    case "splitgld":
                    case "splitcrm":
                        return 5;
                    case "lme":
                    case "grn":
                    case "tqs":
                    case "frs":
                    case "eme":
                        return 22;
                    case "splitlme":
                    case "splitgrn":
                    case "splittqs":
                    case "splitfrs":
                    case "spliteme":
                        return 2;
                    case "tea":
                    case "ptr":
                    case "eth":
                    case "blu":
                    case "nvy":
                        return 33;
                    case "splittea":
                    case "splitptr":
                    case "spliteth":
                    case "splitblu":
                    case "splitnvy":
                        return 13;
                    case "lvn":
                    case "ppl":
                    case "sns":
                        return 26;
                    case "splitlvn":
                    case "splitppl":
                    case "splitsns":
                        return 6;
                    case "rse":
                    case "pnk":
                        return 20;
                    case "splitrse":
                    case "splitpnk":
                        return 0;
                    case "rbw":
                        return 21;
                    case "splitrbw":
                        return 1;
            }
            case "letnev":
                switch (colour.getAlias())
                {
                    case "lgy":
                    case "gry":
                    case "blk":
                        return 34;
                    case "splitlgy":
                    case "splitgry":
                    case "splitblk":
                    case "orca":
                        return 14;
                    case "red":
                    case "bld":
                        return 36;
                    case "splitred":
                    case "splitbld":
                        return 16;
                    case "org":
                        return 24;
                    case "splitorg":
                        return 4;
                    case "tan":
                    case "bwn":
                    case "chk":
                        return 27;
                    case "splittan":
                    case "splitbwn":
                    case "splitchk":
                        return 7;
                    case "spr":
                    case "ylw":
                    case "gld":
                    case "crm":
                        return 23;
                    case "splitspr":
                    case "splitylw":
                    case "splitgld":
                    case "splitcrm":
                        return 3;
                    case "lme":
                    case "grn":
                    case "tqs":
                    case "frs":
                    case "eme":
                        return 20;
                    case "splitlme":
                    case "splitgrn":
                    case "splittqs":
                    case "splitfrs":
                    case "spliteme":
                        return 0;
                    case "tea":
                    case "ptr":
                    case "eth":
                    case "blu":
                    case "nvy":
                        return 27;
                    case "splittea":
                    case "splitptr":
                    case "spliteth":
                    case "splitblu":
                    case "splitnvy":
                        return 7;
                    case "lvn":
                    case "ppl":
                    case "sns":
                        return 23;
                    case "splitlvn":
                    case "splitppl":
                    case "splitsns":
                        return 3;
                    case "rse":
                    case "pnk":
                        return 21;
                    case "splitrse":
                    case "splitpnk":
                        return 1;
                    case "rbw":
                        return 21;
                    case "splitrbw":
                        return 1;
            }
            case "mentak":
                switch (colour.getAlias())
                {
                    case "lgy":
                    case "gry":
                    case "blk":
                        return 28;
                    case "splitlgy":
                    case "splitgry":
                    case "splitblk":
                    case "orca":
                        return 8;
                    case "red":
                    case "bld":
                        return 24;
                    case "splitred":
                    case "splitbld":
                        return 4;
                    case "org":
                        return 36;
                    case "splitorg":
                        return 16;
                    case "tan":
                    case "bwn":
                    case "chk":
                        return 30;
                    case "splittan":
                    case "splitbwn":
                    case "splitchk":
                        return 10;
                    case "spr":
                    case "ylw":
                    case "gld":
                    case "crm":
                        return 34;
                    case "splitspr":
                    case "splitylw":
                    case "splitgld":
                    case "splitcrm":
                        return 14;
                    case "lme":
                    case "grn":
                    case "tqs":
                    case "frs":
                    case "eme":
                        return 21;
                    case "splitlme":
                    case "splitgrn":
                    case "splittqs":
                    case "splitfrs":
                    case "spliteme":
                        return 1;
                    case "tea":
                    case "ptr":
                    case "eth":
                    case "blu":
                    case "nvy":
                        return 21;
                    case "splittea":
                    case "splitptr":
                    case "spliteth":
                    case "splitblu":
                    case "splitnvy":
                        return 1;
                    case "lvn":
                    case "ppl":
                    case "sns":
                        return 24;
                    case "splitlvn":
                    case "splitppl":
                    case "splitsns":
                        return 4;
                    case "rse":
                    case "pnk":
                        return 23;
                    case "splitrse":
                    case "splitpnk":
                        return 3;
                    case "rbw":
                        return 25;
                    case "splitrbw":
                        return 5;
            }
            case "muaat":
                switch (colour.getAlias())
                {
                    case "lgy":
                    case "gry":
                    case "blk":
                        return 25;
                    case "splitlgy":
                    case "splitgry":
                    case "splitblk":
                    case "orca":
                        return 5;
                    case "red":
                    case "bld":
                        return 37;
                    case "splitred":
                    case "splitbld":
                        return 17;
                    case "org":
                        return 36;
                    case "splitorg":
                        return 16;
                    case "tan":
                    case "bwn":
                    case "chk":
                        return 24;
                    case "splittan":
                    case "splitbwn":
                    case "splitchk":
                        return 4;
                    case "spr":
                    case "ylw":
                    case "gld":
                    case "crm":
                        return 30;
                    case "splitspr":
                    case "splitylw":
                    case "splitgld":
                    case "splitcrm":
                        return 10;
                    case "lme":
                    case "grn":
                    case "tqs":
                    case "frs":
                    case "eme":
                        return 20;
                    case "splitlme":
                    case "splitgrn":
                    case "splittqs":
                    case "splitfrs":
                    case "spliteme":
                        return 0;
                    case "tea":
                    case "ptr":
                    case "eth":
                    case "blu":
                    case "nvy":
                        return 20;
                    case "splittea":
                    case "splitptr":
                    case "spliteth":
                    case "splitblu":
                    case "splitnvy":
                        return 0;
                    case "lvn":
                    case "ppl":
                    case "sns":
                        return 21;
                    case "splitlvn":
                    case "splitppl":
                    case "splitsns":
                        return 1;
                    case "rse":
                    case "pnk":
                        return 23;
                    case "splitrse":
                    case "splitpnk":
                        return 3;
                    case "rbw":
                        return 29;
                    case "splitrbw":
                        return 9;
            }
            case "naalu":
                switch (colour.getAlias())
                {
                    case "lgy":
                    case "gry":
                    case "blk":
                        return 25;
                    case "splitlgy":
                    case "splitgry":
                    case "splitblk":
                    case "orca":
                        return 5;
                    case "red":
                    case "bld":
                        return 22;
                    case "splitred":
                    case "splitbld":
                        return 2;
                    case "org":
                        return 26;
                    case "splitorg":
                        return 6;
                    case "tan":
                    case "bwn":
                    case "chk":
                        return 27;
                    case "splittan":
                    case "splitbwn":
                    case "splitchk":
                        return 7;
                    case "spr":
                    case "ylw":
                    case "gld":
                    case "crm":
                        return 29;
                    case "splitspr":
                    case "splitylw":
                    case "splitgld":
                    case "splitcrm":
                        return 9;
                    case "lme":
                    case "grn":
                    case "tqs":
                    case "frs":
                    case "eme":
                        return 37;
                    case "splitlme":
                    case "splitgrn":
                    case "splittqs":
                    case "splitfrs":
                    case "spliteme":
                        return 17;
                    case "tea":
                    case "ptr":
                    case "eth":
                    case "blu":
                    case "nvy":
                        return 25;
                    case "splittea":
                    case "splitptr":
                    case "spliteth":
                    case "splitblu":
                    case "splitnvy":
                        return 5;
                    case "lvn":
                    case "ppl":
                    case "sns":
                        return 22;
                    case "splitlvn":
                    case "splitppl":
                    case "splitsns":
                        return 2;
                    case "rse":
                    case "pnk":
                        return 21;
                    case "splitrse":
                    case "splitpnk":
                        return 1;
                    case "rbw":
                        return 29;
                    case "splitrbw":
                        return 9;
            }
            case "nekro":
                switch (colour.getAlias())
                {
                    case "lgy":
                    case "gry":
                    case "blk":
                        return 34;
                    case "splitlgy":
                    case "splitgry":
                    case "splitblk":
                    case "orca":
                        return 14;
                    case "red":
                    case "bld":
                        return 40;
                    case "splitred":
                    case "splitbld":
                        return 20;
                    case "org":
                        return 22;
                    case "splitorg":
                        return 2;
                    case "tan":
                    case "bwn":
                    case "chk":
                        return 24;
                    case "splittan":
                    case "splitbwn":
                    case "splitchk":
                        return 4;
                    case "spr":
                    case "ylw":
                    case "gld":
                    case "crm":
                        return 21;
                    case "splitspr":
                    case "splitylw":
                    case "splitgld":
                    case "splitcrm":
                        return 1;
                    case "lme":
                    case "grn":
                    case "tqs":
                    case "frs":
                    case "eme":
                        return 20;
                    case "splitlme":
                    case "splitgrn":
                    case "splittqs":
                    case "splitfrs":
                    case "spliteme":
                        return 0;
                    case "tea":
                    case "ptr":
                    case "eth":
                    case "blu":
                    case "nvy":
                        return 20;
                    case "splittea":
                    case "splitptr":
                    case "spliteth":
                    case "splitblu":
                    case "splitnvy":
                        return 0;
                    case "lvn":
                    case "ppl":
                    case "sns":
                        return 22;
                    case "splitlvn":
                    case "splitppl":
                    case "splitsns":
                        return 2;
                    case "rse":
                    case "pnk":
                        return 22;
                    case "splitrse":
                    case "splitpnk":
                        return 2;
                    case "rbw":
                        return 21;
                    case "splitrbw":
                        return 1;
            }
            case "saar":
                switch (colour.getAlias())
                {
                    case "lgy":
                    case "gry":
                    case "blk":
                        return 27;
                    case "splitlgy":
                    case "splitgry":
                    case "splitblk":
                    case "orca":
                        return 7;
                    case "red":
                    case "bld":
                        return 24;
                    case "splitred":
                    case "splitbld":
                        return 4;
                    case "org":
                        return 32;
                    case "splitorg":
                        return 12;
                    case "tan":
                    case "bwn":
                    case "chk":
                        return 36;
                    case "splittan":
                    case "splitbwn":
                    case "splitchk":
                        return 6;
                    case "spr":
                    case "ylw":
                    case "gld":
                    case "crm":
                        return 33;
                    case "splitspr":
                    case "splitylw":
                    case "splitgld":
                    case "splitcrm":
                        return 13;
                    case "lme":
                    case "grn":
                    case "tqs":
                    case "frs":
                    case "eme":
                        return 29;
                    case "splitlme":
                    case "splitgrn":
                    case "splittqs":
                    case "splitfrs":
                    case "spliteme":
                        return 9;
                    case "tea":
                    case "ptr":
                    case "eth":
                    case "blu":
                    case "nvy":
                        return 27;
                    case "splittea":
                    case "splitptr":
                    case "spliteth":
                    case "splitblu":
                    case "splitnvy":
                        return 7;
                    case "lvn":
                    case "ppl":
                    case "sns":
                        return 22;
                    case "splitlvn":
                    case "splitppl":
                    case "splitsns":
                        return 2;
                    case "rse":
                    case "pnk":
                        return 20;
                    case "splitrse":
                    case "splitpnk":
                        return 0;
                    case "rbw":
                        return 25;
                    case "splitrbw":
                        return 5;
            }
            case "sardakk":
                switch (colour.getAlias())
                {
                    case "lgy":
                    case "gry":
                    case "blk":
                        return 35;
                    case "splitlgy":
                    case "splitgry":
                    case "splitblk":
                    case "orca":
                        return 15;
                    case "red":
                    case "bld":
                        return 38;
                    case "splitred":
                    case "splitbld":
                        return 18;
                    case "org":
                        return 25;
                    case "splitorg":
                        return 5;
                    case "tan":
                    case "bwn":
                    case "chk":
                        return 30;
                    case "splittan":
                    case "splitbwn":
                    case "splitchk":
                        return 10;
                    case "spr":
                    case "ylw":
                    case "gld":
                    case "crm":
                        return 24;
                    case "splitspr":
                    case "splitylw":
                    case "splitgld":
                    case "splitcrm":
                        return 4;
                    case "lme":
                    case "grn":
                    case "tqs":
                    case "frs":
                    case "eme":
                        return 26;
                    case "splitlme":
                    case "splitgrn":
                    case "splittqs":
                    case "splitfrs":
                    case "spliteme":
                        return 6;
                    case "tea":
                    case "ptr":
                    case "eth":
                    case "blu":
                    case "nvy":
                        return 20;
                    case "splittea":
                    case "splitptr":
                    case "spliteth":
                    case "splitblu":
                    case "splitnvy":
                        return 0;
                    case "lvn":
                    case "ppl":
                    case "sns":
                        return 21;
                    case "splitlvn":
                    case "splitppl":
                    case "splitsns":
                        return 1;
                    case "rse":
                    case "pnk":
                        return 21;
                    case "splitrse":
                    case "splitpnk":
                        return 1;
                    case "rbw":
                        return 21;
                    case "splitrbw":
                        return 1;
            }
            case "sol":
                switch (colour.getAlias())
                {
                    case "lgy":
                    case "gry":
                    case "blk":
                        return 21;
                    case "splitlgy":
                    case "splitgry":
                    case "splitblk":
                    case "orca":
                        return 1;
                    case "red":
                    case "bld":
                        return 21;
                    case "splitred":
                    case "splitbld":
                        return 1;
                    case "org":
                        return 21;
                    case "splitorg":
                        return 1;
                    case "tan":
                    case "bwn":
                    case "chk":
                        return 27;
                    case "splittan":
                    case "splitbwn":
                    case "splitchk":
                        return 7;
                    case "spr":
                    case "ylw":
                    case "gld":
                    case "crm":
                        return 32;
                    case "splitspr":
                    case "splitylw":
                    case "splitgld":
                    case "splitcrm":
                        return 12;
                    case "lme":
                    case "grn":
                    case "tqs":
                    case "frs":
                    case "eme":
                        return 29;
                    case "splitlme":
                    case "splitgrn":
                    case "splittqs":
                    case "splitfrs":
                    case "spliteme":
                        return 9;
                    case "tea":
                    case "ptr":
                    case "eth":
                    case "blu":
                    case "nvy":
                        return 37;
                    case "splittea":
                    case "splitptr":
                    case "spliteth":
                    case "splitblu":
                    case "splitnvy":
                        return 17;
                    case "lvn":
                    case "ppl":
                    case "sns":
                        return 22;
                    case "splitlvn":
                    case "splitppl":
                    case "splitsns":
                        return 2;
                    case "rse":
                    case "pnk":
                        return 21;
                    case "splitrse":
                    case "splitpnk":
                        return 1;
                    case "rbw":
                        return 29;
                    case "splitrbw":
                        return 9;
            }
            case "winnu":
                switch (colour.getAlias())
                {
                    case "lgy":
                    case "gry":
                    case "blk":
                        return 21;
                    case "splitlgy":
                    case "splitgry":
                    case "splitblk":
                    case "orca":
                        return 1;
                    case "red":
                    case "bld":
                        return 23;
                    case "splitred":
                    case "splitbld":
                        return 3;
                    case "org":
                        return 28;
                    case "splitorg":
                        return 8;
                    case "tan":
                    case "bwn":
                    case "chk":
                        return 24;
                    case "splittan":
                    case "splitbwn":
                    case "splitchk":
                        return 4;
                    case "spr":
                    case "ylw":
                    case "gld":
                    case "crm":
                        return 34;
                    case "splitspr":
                    case "splitylw":
                    case "splitgld":
                    case "splitcrm":
                        return 14;
                    case "lme":
                    case "grn":
                    case "tqs":
                    case "frs":
                    case "eme":
                        return 21;
                    case "splitlme":
                    case "splitgrn":
                    case "splittqs":
                    case "splitfrs":
                    case "spliteme":
                        return 1;
                    case "tea":
                    case "ptr":
                    case "eth":
                    case "blu":
                    case "nvy":
                        return 25;
                    case "splittea":
                    case "splitptr":
                    case "spliteth":
                    case "splitblu":
                    case "splitnvy":
                        return 5;
                    case "lvn":
                    case "ppl":
                    case "sns":
                        return 35;
                    case "splitlvn":
                    case "splitppl":
                    case "splitsns":
                        return 15;
                    case "rse":
                    case "pnk":
                        return 29;
                    case "splitrse":
                    case "splitpnk":
                        return 9;
                    case "rbw":
                        return 33;
                    case "splitrbw":
                        return 13;
            }
            case "xxcha":
                switch (colour.getAlias())
                {
                    case "lgy":
                    case "gry":
                    case "blk":
                        return 21;
                    case "splitlgy":
                    case "splitgry":
                    case "splitblk":
                    case "orca":
                        return 1;
                    case "red":
                    case "bld":
                        return 20;
                    case "splitred":
                    case "splitbld":
                        return 0;
                    case "org":
                        return 21;
                    case "splitorg":
                        return 1;
                    case "tan":
                    case "bwn":
                    case "chk":
                        return 27;
                    case "splittan":
                    case "splitbwn":
                    case "splitchk":
                        return 7;
                    case "spr":
                    case "ylw":
                    case "gld":
                    case "crm":
                        return 27;
                    case "splitspr":
                    case "splitylw":
                    case "splitgld":
                    case "splitcrm":
                        return 7;
                    case "lme":
                    case "grn":
                    case "tqs":
                    case "frs":
                    case "eme":
                        return 35;
                    case "splitlme":
                    case "splitgrn":
                    case "splittqs":
                    case "splitfrs":
                    case "spliteme":
                        return 15;
                    case "tea":
                    case "ptr":
                    case "eth":
                    case "blu":
                    case "nvy":
                        return 30;
                    case "splittea":
                    case "splitptr":
                    case "spliteth":
                    case "splitblu":
                    case "splitnvy":
                        return 10;
                    case "lvn":
                    case "ppl":
                    case "sns":
                        return 21;
                    case "splitlvn":
                    case "splitppl":
                    case "splitsns":
                        return 1;
                    case "rse":
                    case "pnk":
                        return 21;
                    case "splitrse":
                    case "splitpnk":
                        return 1;
                    case "rbw":
                        return 29;
                    case "splitrbw":
                        return 9;
            }
            case "yin":
                switch (colour.getAlias())
                {
                    case "lgy":
                    case "gry":
                    case "blk":
                        return 31;
                    case "splitlgy":
                    case "splitgry":
                    case "splitblk":
                    case "orca":
                        return 11;
                    case "red":
                    case "bld":
                        return 23;
                    case "splitred":
                    case "splitbld":
                        return 3;
                    case "org":
                        return 21;
                    case "splitorg":
                        return 1;
                    case "tan":
                    case "bwn":
                    case "chk":
                        return 27;
                    case "splittan":
                    case "splitbwn":
                    case "splitchk":
                        return 7;
                    case "spr":
                    case "ylw":
                    case "gld":
                    case "crm":
                        return 28;
                    case "splitspr":
                    case "splitylw":
                    case "splitgld":
                    case "splitcrm":
                        return 8;
                    case "lme":
                    case "grn":
                    case "tqs":
                    case "frs":
                    case "eme":
                        return 25;
                    case "splitlme":
                    case "splitgrn":
                    case "splittqs":
                    case "splitfrs":
                    case "spliteme":
                        return 5;
                    case "tea":
                    case "ptr":
                    case "eth":
                    case "blu":
                    case "nvy":
                        return 21;
                    case "splittea":
                    case "splitptr":
                    case "spliteth":
                    case "splitblu":
                    case "splitnvy":
                        return 1;
                    case "lvn":
                    case "ppl":
                    case "sns":
                        return 35;
                    case "splitlvn":
                    case "splitppl":
                    case "splitsns":
                        return 15;
                    case "rse":
                    case "pnk":
                        return 28;
                    case "splitrse":
                    case "splitpnk":
                        return 8;
                    case "rbw":
                        return 25;
                    case "splitrbw":
                        return 5;
            }
            case "yssaril":
                switch (colour.getAlias())
                {
                    case "lgy":
                    case "gry":
                    case "blk":
                        return 26;
                    case "splitlgy":
                    case "splitgry":
                    case "splitblk":
                    case "orca":
                        return 6;
                    case "red":
                    case "bld":
                        return 24;
                    case "splitred":
                    case "splitbld":
                        return 4;
                    case "org":
                        return 23;
                    case "splitorg":
                        return 3;
                    case "tan":
                    case "bwn":
                    case "chk":
                        return 30;
                    case "splittan":
                    case "splitbwn":
                    case "splitchk":
                        return 10;
                    case "spr":
                    case "ylw":
                    case "gld":
                    case "crm":
                        return 27;
                    case "splitspr":
                    case "splitylw":
                    case "splitgld":
                    case "splitcrm":
                        return 7;
                    case "lme":
                    case "grn":
                    case "tqs":
                    case "frs":
                    case "eme":
                        return 36;
                    case "splitlme":
                    case "splitgrn":
                    case "splittqs":
                    case "splitfrs":
                    case "spliteme":
                        return 16;
                    case "tea":
                    case "ptr":
                    case "eth":
                    case "blu":
                    case "nvy":
                        return 22;
                    case "splittea":
                    case "splitptr":
                    case "spliteth":
                    case "splitblu":
                    case "splitnvy":
                        return 2;
                    case "lvn":
                    case "ppl":
                    case "sns":
                        return 23;
                    case "splitlvn":
                    case "splitppl":
                    case "splitsns":
                        return 3;
                    case "rse":
                    case "pnk":
                        return 20;
                    case "splitrse":
                    case "splitpnk":
                        return 0;
                    case "rbw":
                        return 21;
                    case "splitrbw":
                        return 1;
            }
            case "argent":
                switch (colour.getAlias())
                {
                    case "lgy":
                    case "gry":
                    case "blk":
                        return 23;
                    case "splitlgy":
                    case "splitgry":
                    case "splitblk":
                    case "orca":
                        return 3;
                    case "red":
                    case "bld":
                        return 28;
                    case "splitred":
                    case "splitbld":
                        return 8;
                    case "org":
                        return 39;
                    case "splitorg":
                        return 19;
                    case "tan":
                    case "bwn":
                    case "chk":
                        return 30;
                    case "splittan":
                    case "splitbwn":
                    case "splitchk":
                        return 10;
                    case "spr":
                    case "ylw":
                    case "gld":
                    case "crm":
                        return 29;
                    case "splitspr":
                    case "splitylw":
                    case "splitgld":
                    case "splitcrm":
                        return 9;
                    case "lme":
                    case "grn":
                    case "tqs":
                    case "frs":
                    case "eme":
                        return 25;
                    case "splitlme":
                    case "splitgrn":
                    case "splittqs":
                    case "splitfrs":
                    case "spliteme":
                        return 5;
                    case "tea":
                    case "ptr":
                    case "eth":
                    case "blu":
                    case "nvy":
                        return 21;
                    case "splittea":
                    case "splitptr":
                    case "spliteth":
                    case "splitblu":
                    case "splitnvy":
                        return 1;
                    case "lvn":
                    case "ppl":
                    case "sns":
                        return 21;
                    case "splitlvn":
                    case "splitppl":
                    case "splitsns":
                        return 1;
                    case "rse":
                    case "pnk":
                        return 21;
                    case "splitrse":
                    case "splitpnk":
                        return 1;
                    case "rbw":
                        return 25;
                    case "splitrbw":
                        return 5;
            }
            case "cabal":
                switch (colour.getAlias())
                {
                    case "lgy":
                    case "gry":
                    case "blk":
                        return 30;
                    case "splitlgy":
                    case "splitgry":
                    case "splitblk":
                    case "orca":
                        return 10;
                    case "red":
                    case "bld":
                        return 40;
                    case "splitred":
                    case "splitbld":
                        return 20;
                    case "org":
                        return 25;
                    case "splitorg":
                        return 5;
                    case "tan":
                    case "bwn":
                    case "chk":
                        return 27;
                    case "splittan":
                    case "splitbwn":
                    case "splitchk":
                        return 7;
                    case "spr":
                    case "ylw":
                    case "gld":
                    case "crm":
                        return 21;
                    case "splitspr":
                    case "splitylw":
                    case "splitgld":
                    case "splitcrm":
                        return 1;
                    case "lme":
                    case "grn":
                    case "tqs":
                    case "frs":
                    case "eme":
                        return 20;
                    case "splitlme":
                    case "splitgrn":
                    case "splittqs":
                    case "splitfrs":
                    case "spliteme":
                        return 0;
                    case "tea":
                    case "ptr":
                    case "eth":
                    case "blu":
                    case "nvy":
                        return 24;
                    case "splittea":
                    case "splitptr":
                    case "spliteth":
                    case "splitblu":
                    case "splitnvy":
                        return 4;
                    case "lvn":
                    case "ppl":
                    case "sns":
                        return 24;
                    case "splitlvn":
                    case "splitppl":
                    case "splitsns":
                        return 4;
                    case "rse":
                    case "pnk":
                        return 26;
                    case "splitrse":
                    case "splitpnk":
                        return 6;
                    case "rbw":
                        return 25;
                    case "splitrbw":
                        return 5;
            }
            case "empyrean":
                switch (colour.getAlias())
                {
                    case "lgy":
                    case "gry":
                    case "blk":
                        return 29;
                    case "splitlgy":
                    case "splitgry":
                    case "splitblk":
                    case "orca":
                        return 9;
                    case "red":
                    case "bld":
                        return 26;
                    case "splitred":
                    case "splitbld":
                        return 6;
                    case "org":
                        return 21;
                    case "splitorg":
                        return 1;
                    case "tan":
                    case "bwn":
                    case "chk":
                        return 21;
                    case "splittan":
                    case "splitbwn":
                    case "splitchk":
                        return 1;
                    case "spr":
                    case "ylw":
                    case "gld":
                    case "crm":
                        return 20;
                    case "splitspr":
                    case "splitylw":
                    case "splitgld":
                    case "splitcrm":
                        return 0;
                    case "lme":
                    case "grn":
                    case "tqs":
                    case "frs":
                    case "eme":
                        return 21;
                    case "splitlme":
                    case "splitgrn":
                    case "splittqs":
                    case "splitfrs":
                    case "spliteme":
                        return 1;
                    case "tea":
                    case "ptr":
                    case "eth":
                    case "blu":
                    case "nvy":
                        return 29;
                    case "splittea":
                    case "splitptr":
                    case "spliteth":
                    case "splitblu":
                    case "splitnvy":
                        return 9;
                    case "lvn":
                    case "ppl":
                    case "sns":
                        return 40;
                    case "splitlvn":
                    case "splitppl":
                    case "splitsns":
                        return 20;
                    case "rse":
                    case "pnk":
                        return 28;
                    case "splitrse":
                    case "splitpnk":
                        return 8;
                    case "rbw":
                        return 33;
                    case "splitrbw":
                        return 13;
            }
            case "mahact":
                switch (colour.getAlias())
                {
                    case "lgy":
                    case "gry":
                    case "blk":
                        return 28;
                    case "splitlgy":
                    case "splitgry":
                    case "splitblk":
                    case "orca":
                        return 8;
                    case "red":
                    case "bld":
                        return 26;
                    case "splitred":
                    case "splitbld":
                        return 6;
                    case "org":
                        return 26;
                    case "splitorg":
                        return 6;
                    case "tan":
                    case "bwn":
                    case "chk":
                        return 24;
                    case "splittan":
                    case "splitbwn":
                    case "splitchk":
                        return 4;
                    case "spr":
                    case "ylw":
                    case "gld":
                    case "crm":
                        return 39;
                    case "splitspr":
                    case "splitylw":
                    case "splitgld":
                    case "splitcrm":
                        return 19;
                    case "lme":
                    case "grn":
                    case "tqs":
                    case "frs":
                    case "eme":
                        return 24;
                    case "splitlme":
                    case "splitgrn":
                    case "splittqs":
                    case "splitfrs":
                    case "spliteme":
                        return 4;
                    case "tea":
                    case "ptr":
                    case "eth":
                    case "blu":
                    case "nvy":
                        return 25;
                    case "splittea":
                    case "splitptr":
                    case "spliteth":
                    case "splitblu":
                    case "splitnvy":
                        return 5;
                    case "lvn":
                    case "ppl":
                    case "sns":
                        return 32;
                    case "splitlvn":
                    case "splitppl":
                    case "splitsns":
                        return 12;
                    case "rse":
                    case "pnk":
                        return 24;
                    case "splitrse":
                    case "splitpnk":
                        return 4;
                    case "rbw":
                        return 33;
                    case "splitrbw":
                        return 13;
            }
            case "nomad":
                switch (colour.getAlias())
                {
                    case "lgy":
                    case "gry":
                    case "blk":
                        return 25;
                    case "splitlgy":
                    case "splitgry":
                    case "splitblk":
                    case "orca":
                        return 5;
                    case "red":
                    case "bld":
                        return 22;
                    case "splitred":
                    case "splitbld":
                        return 2;
                    case "org":
                        return 21;
                    case "splitorg":
                        return 1;
                    case "tan":
                    case "bwn":
                    case "chk":
                        return 21;
                    case "splittan":
                    case "splitbwn":
                    case "splitchk":
                        return 1;
                    case "spr":
                    case "ylw":
                    case "gld":
                    case "crm":
                        return 23;
                    case "splitspr":
                    case "splitylw":
                    case "splitgld":
                    case "splitcrm":
                        return 3;
                    case "lme":
                    case "grn":
                    case "tqs":
                    case "frs":
                    case "eme":
                        return 26;
                    case "splitlme":
                    case "splitgrn":
                    case "splittqs":
                    case "splitfrs":
                    case "spliteme":
                        return 6;
                    case "tea":
                    case "ptr":
                    case "eth":
                    case "blu":
                    case "nvy":
                        return 36;
                    case "splittea":
                    case "splitptr":
                    case "spliteth":
                    case "splitblu":
                    case "splitnvy":
                        return 16;
                    case "lvn":
                    case "ppl":
                    case "sns":
                        return 33;
                    case "splitlvn":
                    case "splitppl":
                    case "splitsns":
                        return 13;
                    case "rse":
                    case "pnk":
                        return 27;
                    case "splitrse":
                    case "splitpnk":
                        return 7;
                    case "rbw":
                        return 33;
                    case "splitrbw":
                        return 13;
            }
            case "naaz":
                switch (colour.getAlias())
                {
                    case "lgy":
                    case "gry":
                    case "blk":
                        return 24;
                    case "splitlgy":
                    case "splitgry":
                    case "splitblk":
                    case "orca":
                        return 4;
                    case "red":
                    case "bld":
                        return 23;
                    case "splitred":
                    case "splitbld":
                        return 3;
                    case "org":
                        return 23;
                    case "splitorg":
                        return 3;
                    case "tan":
                    case "bwn":
                    case "chk":
                        return 30;
                    case "splittan":
                    case "splitbwn":
                    case "splitchk":
                        return 10;
                    case "spr":
                    case "ylw":
                    case "gld":
                    case "crm":
                        return 26;
                    case "splitspr":
                    case "splitylw":
                    case "splitgld":
                    case "splitcrm":
                        return 6;
                    case "lme":
                    case "grn":
                    case "tqs":
                    case "frs":
                    case "eme":
                        return 39;
                    case "splitlme":
                    case "splitgrn":
                    case "splittqs":
                    case "splitfrs":
                    case "spliteme":
                        return 19;
                    case "tea":
                    case "ptr":
                    case "eth":
                    case "blu":
                    case "nvy":
                        return 21;
                    case "splittea":
                    case "splitptr":
                    case "spliteth":
                    case "splitblu":
                    case "splitnvy":
                        return 1;
                    case "lvn":
                    case "ppl":
                    case "sns":
                        return 24;
                    case "splitlvn":
                    case "splitppl":
                    case "splitsns":
                        return 4;
                    case "rse":
                    case "pnk":
                        return 21;
                    case "splitrse":
                    case "splitpnk":
                        return 1;
                    case "rbw":
                        return 29;
                    case "splitrbw":
                        return 9;
            }
            case "titans":
                switch (colour.getAlias())
                {
                    case "lgy":
                    case "gry":
                    case "blk":
                        return 22;
                    case "splitlgy":
                    case "splitgry":
                    case "splitblk":
                    case "orca":
                        return 2;
                    case "red":
                    case "bld":
                        return 25;
                    case "splitred":
                    case "splitbld":
                        return 5;
                    case "org":
                        return 24;
                    case "splitorg":
                        return 4;
                    case "tan":
                    case "bwn":
                    case "chk":
                        return 27;
                    case "splittan":
                    case "splitbwn":
                    case "splitchk":
                        return 7;
                    case "spr":
                    case "ylw":
                    case "gld":
                    case "crm":
                        return 25;
                    case "splitspr":
                    case "splitylw":
                    case "splitgld":
                    case "splitcrm":
                        return 5;
                    case "lme":
                    case "grn":
                    case "tqs":
                    case "frs":
                    case "eme":
                        return 24;
                    case "splitlme":
                    case "splitgrn":
                    case "splittqs":
                    case "splitfrs":
                    case "spliteme":
                        return 4;
                    case "tea":
                    case "ptr":
                    case "eth":
                    case "blu":
                    case "nvy":
                        return 23;
                    case "splittea":
                    case "splitptr":
                    case "spliteth":
                    case "splitblu":
                    case "splitnvy":
                        return 3;
                    case "lvn":
                    case "ppl":
                    case "sns":
                        return 26;
                    case "splitlvn":
                    case "splitppl":
                    case "splitsns":
                        return 6;
                    case "rse":
                    case "pnk":
                        return 40;
                    case "splitrse":
                    case "splitpnk":
                        return 20;
                    case "rbw":
                        return 25;
                    case "splitrbw":
                        return 5;
            }
            case "keleresa":
            case "keleresm":
            case "keleresx":
                switch (colour.getAlias())
                {
                    case "lgy":
                    case "gry":
                    case "blk":
                        return 33;
                    case "splitlgy":
                    case "splitgry":
                    case "splitblk":
                    case "orca":
                        return 13;
                    case "red":
                    case "bld":
                        return 21;
                    case "splitred":
                    case "splitbld":
                        return 1;
                    case "org":
                        return 23;
                    case "splitorg":
                        return 3;
                    case "tan":
                    case "bwn":
                    case "chk":
                        return 30;
                    case "splittan":
                    case "splitbwn":
                    case "splitchk":
                        return 10;
                    case "spr":
                    case "ylw":
                    case "gld":
                    case "crm":
                        return 27;
                    case "splitspr":
                    case "splitylw":
                    case "splitgld":
                    case "splitcrm":
                        return 7;
                    case "lme":
                    case "grn":
                    case "tqs":
                    case "frs":
                    case "eme":
                        return 26;
                    case "splitlme":
                    case "splitgrn":
                    case "splittqs":
                    case "splitfrs":
                    case "spliteme":
                        return 6;
                    case "tea":
                    case "ptr":
                    case "eth":
                    case "blu":
                    case "nvy":
                        return 32;
                    case "splittea":
                    case "splitptr":
                    case "spliteth":
                    case "splitblu":
                    case "splitnvy":
                        return 12;
                    case "lvn":
                    case "ppl":
                    case "sns":
                        return 35;
                    case "splitlvn":
                    case "splitppl":
                    case "splitsns":
                        return 15;
                    case "rse":
                    case "pnk":
                        return 34;
                    case "splitrse":
                    case "splitpnk":
                        return 4;
                    case "rbw":
                        return 37;
                    case "splitrbw":
                        return 7;
            }
        }
        if (colour.getAlias().startsWith("split") || colour.getAlias().equals("orca"))
        {
            return 5;
        }
    return 15;
    }
}