package ti4.helpers;

import java.awt.*;

public class Constants {
    public static final String SHOW_MAP = "show_map";
    public static final String MAP_NAME = "map_name";
    public static final String CONFIRM = "confirm";
    public static final String SHUTDOWN = "shutdown";
    public static final String SET_MAP = "set_map";
    public static final String SAVE_MAPS = "save_maps";
    public static final String LIST_TILES = "list_tiles";
    public static final String LIST_UNITS = "list_units";
    public static final String LIST_MAPS = "list_maps";
    public static final String CREATE_MAP = "create_map";
    public static final String DELETE_MAP = "delete_map";
    public static final String POSITION = "position";
    public static final String TILE_NAME = "tile_name";
    public static final String HELP = "help";
    public static final String PLANET_NAME = "planet_name";
    public static final String TILE_LIST = "tile_list";
    public static final String UNIT_NAMES = "unit_names";
    public static final String COLOR = "color";
    public static final String ADD_TILE = "add_tile";
    public static final String ADD_CC = "add_cc";
    public static final String ADD_CONTROL = "add_control";
    public static final String REMOVE_CC = "remove_cc";
    public static final String REMOVE_CONTROL = "remove_control";
    public static final String REMOVE_ALL_CC = "remove_all_cc";
    public static final String REMOVE_TILE = "remove_tile";
    public static final String ADD_TILE_LIST = "add_tile_list";
    public static final String ADD_UNITS = "add_units";
    public static final String REMOVE_UNITS = "remove_units";
    public static final String REMOVE_ALL_UNITS = "remove_all_units";
    public static final String SPACE = "space";
    public static final String COMMAND = "command_";
    public static final String CONTROL = "control_";
    public static final String GF = "gf";
    public static final String FF = "ff";
    public static final String BULK_GF = "_tkn_gf.png";
    public static final String BULK_FF = "_tkn_ff.png";
    public static final String COLOR_GF = "_gf.png";
    public static final String COLOR_FF = "_ff.png";
    public static final String SETUP6 = "setup6";
    public static final String MALLICE = "mallicelocked";
    public static final String MR = "mr";
    public static final int SPACE_RADIUS = 115;
    public static final int RADIUS = 45;
    public static final Point SPACE_CENTER_POSITION = new Point(172,150);
}
