create table active_lease (
    lease_key text not null primary key,
    heartbeat_at timestamp(6) with time zone,
    instance_id text,
    lease_expires_at timestamp(6) with time zone
);

create table bot_discord_message (
    message_id bigint not null primary key,
    content text,
    created_at_epoch_millis bigint not null
);

create table combat_observation (
    id bigint generated by default as identity primary key,
    started_at timestamp(6) not null,
    game_name text not null,
    tile_position text not null,
    attacker_faction text not null,
    defender_faction text not null,
    attacker_strength double precision not null,
    defender_strength double precision not null,
    attacker_hp double precision not null,
    defender_hp double precision not null,
    attacker_expected_hits double precision not null,
    defender_expected_hits double precision not null,
    fairness_ratio double precision not null,
    joint_score double precision not null
);

create table combat_candidate (
    id bigint generated by default as identity primary key,
    observation_id bigint not null unique,
    status text not null,
    promotion_status text not null,
    next_event_sequence integer not null,
    started_at timestamp(6) not null,
    resolved_at timestamp(6),
    pending_resolution_started_at timestamp(6),
    promoted_at timestamp(6),
    mentak_preview_posted_at timestamp(6),
    game_name text not null,
    tile_position text not null,
    attacker_faction text not null,
    defender_faction text not null,
    winner_faction text,
    loser_faction text,
    resolution_reason text,
    cancellation_reason text,
    pre_replay_context_text text,
    initial_render_snapshot_json text,
    replay_abilities_json text,
    promotion_score double precision,
    side_bet_compatible boolean not null default false,
    attacker_destroyer_count integer not null default 0,
    defender_destroyer_count integer not null default 0,
    attacker_has_assault_cannon boolean not null default false,
    defender_has_assault_cannon boolean not null default false,
    attacker_hp double precision,
    defender_hp double precision,
    attacker_strength double precision,
    defender_strength double precision,
    attacker_rolled_afb boolean not null default false,
    defender_rolled_afb boolean not null default false,
    attacker_afb_whiff boolean not null default false,
    defender_afb_whiff boolean not null default false,
    attacker_skipped_afb boolean not null default false,
    defender_skipped_afb boolean not null default false,
    attacker_round_one_whiff boolean not null default false,
    defender_round_one_whiff boolean not null default false,
    attacker_round_one_slam boolean not null default false,
    defender_round_one_slam boolean not null default false,
    attacker_played_morale_boost boolean not null default false,
    defender_played_morale_boost boolean not null default false,
    attacker_played_shields_holding boolean not null default false,
    defender_played_shields_holding boolean not null default false,
    attacker_played_direct_hit boolean not null default false,
    defender_played_direct_hit boolean not null default false,
    attacker_played_fighter_prototype boolean not null default false,
    defender_played_fighter_prototype boolean not null default false,
    winner_one_hp_remaining boolean not null default false,
    winner_remaining_hp double precision
);

create table combat_candidate_event (
    id bigint generated by default as identity primary key,
    candidate_id bigint not null,
    occurred_at timestamp(6) not null,
    sequence_number integer not null,
    event_type text not null,
    round_number integer,
    actor_faction text,
    summary_text text not null,
    payload_json text
);

create table combat_contest (
    id bigint generated by default as identity primary key,
    candidate_id bigint not null unique,
    posted_at timestamp(6),
    public_channel_id bigint,
    public_message_id bigint,
    public_thread_id bigint,
    side_bet_summary_message_id bigint,
    side_bet_attacker_button_message_id bigint,
    side_bet_defender_button_message_id bigint,
    side_bet_market_posted_at timestamp(6),
    side_bet_payout_model text,
    replay_status text not null,
    replay_start_at timestamp(6),
    next_replay_at timestamp(6),
    next_event_sequence integer not null,
    replay_completed_at timestamp(6),
    pre_replay_context_posted_at timestamp(6),
    leaderboard_posted_at timestamp(6),
    replay_error text
);

create table combat_contest_side_bets (
    id bigint generated by default as identity primary key,
    contest_id bigint not null,
    discord_user_id text not null,
    discord_user_name text not null,
    bet_type text not null,
    target_faction text not null,
    offered_profit_points integer,
    placed_at timestamp(6) not null,
    resolved_at timestamp(6)
);

create table combat_replay_hacan_market_compact_decision (
    id bigint generated by default as identity primary key,
    contest_id bigint not null,
    decided_at timestamp(6) not null,
    constraint uk_hacan_market_compact_decision_contest unique (contest_id)
);

create table combat_replay_hacan_subsidy (
    id bigint generated by default as identity primary key,
    contest_id bigint not null,
    bet_type text not null,
    target_faction text not null,
    vote_count integer not null,
    selected_at timestamp(6) not null,
    constraint uk_hacan_subsidy_contest_bet unique (contest_id, bet_type, target_faction)
);

create table combat_replay_hacan_subsidy_vote (
    id bigint generated by default as identity primary key,
    contest_id bigint not null,
    discord_user_id text not null,
    discord_user_name text not null,
    bet_type text not null,
    target_faction text not null,
    voted_at timestamp(6) not null,
    constraint uk_hacan_subsidy_vote_user_bet unique (contest_id, discord_user_id, bet_type, target_faction)
);

create table combat_replay_hacan_trade_convoys (
    id bigint generated by default as identity primary key,
    contest_id bigint not null,
    target_house text,
    favor_cost integer not null,
    prediction_bonus integer not null,
    vote_count integer not null,
    selected_at timestamp(6) not null,
    constraint uk_hacan_trade_convoys_contest unique (contest_id)
);

create table combat_replay_hacan_trade_convoys_vote (
    id bigint generated by default as identity primary key,
    contest_id bigint not null,
    target_house text,
    favor_cost integer not null,
    prediction_bonus integer not null,
    discord_user_id text not null,
    discord_user_name text not null,
    voted_at timestamp(6) not null,
    constraint uk_hacan_trade_convoys_vote_contest_user unique (contest_id, discord_user_id)
);

create table combat_replay_house (
    id bigint generated by default as identity primary key,
    discord_user_id text not null,
    discord_user_name text not null,
    house text not null,
    assigned_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    constraint uk_replay_house_user unique (discord_user_id)
);

create table combat_replay_house_ability_use (
    id bigint generated by default as identity primary key,
    candidate_id bigint not null,
    house text not null,
    favor_cost integer not null,
    discord_user_id text not null,
    discord_user_name text not null,
    used_at timestamp(6) not null,
    constraint uk_replay_house_ability_use_candidate_house unique (candidate_id, house)
);

create table combat_replay_house_ability_vote (
    id bigint generated by default as identity primary key,
    candidate_id bigint not null,
    house text not null,
    option_key text not null,
    discord_user_id text not null,
    discord_user_name text not null,
    voted_at timestamp(6) not null,
    constraint uk_house_ability_vote_candidate_house_user unique (candidate_id, house, discord_user_id)
);

create table combat_replay_house_opt_out (
    id bigint generated by default as identity primary key,
    discord_user_id text not null,
    discord_user_name text not null,
    house text not null,
    assigned_at timestamp(6) not null,
    opted_out_at timestamp(6) not null,
    constraint uk_replay_house_opt_out_user unique (discord_user_id)
);

create table combat_replay_house_score (
    id bigint generated by default as identity primary key,
    contest_id bigint not null,
    house text not null,
    prediction_points integer not null,
    side_bet_points integer not null,
    ability_points integer not null,
    favor_points integer,
    total_points integer not null,
    prediction_count integer not null,
    correct_predictions integer not null,
    ability_breakdown_json text not null,
    scored_at timestamp(6) not null,
    constraint uk_replay_house_score_contest_house unique (contest_id, house)
);

create table combat_replay_leaderboard_entry (
    id bigint generated by default as identity primary key,
    discord_user_id text not null,
    discord_user_name text not null,
    total_points integer not null,
    prediction_count integer not null,
    correct_predictions integer not null,
    updated_at timestamp(6) not null,
    constraint uk_replay_leaderboard_user unique (discord_user_id)
);

create table combat_replay_prediction (
    id bigint generated by default as identity primary key,
    contest_id bigint not null,
    locked_at timestamp(6) not null,
    announced_at timestamp(6),
    scored_at timestamp(6),
    attacker_prediction_count integer not null,
    defender_prediction_count integer not null,
    mentak_prediction_override_count integer not null default 0,
    attacker_predictions_json text not null,
    defender_predictions_json text not null,
    constraint uk_replay_prediction_contest unique (contest_id)
);

create table discord_user (
    id text not null primary key,
    name text not null
);

create table game (
    game_name text not null primary key,
    creation_epoch_milliseconds bigint not null,
    ended_epoch_milliseconds bigint,
    round_number integer not null,
    victory_point_goal integer not null,
    is_completed boolean not null,
    is_prophecy_of_kings boolean not null,
    is_thunders_edge boolean not null,
    is_fracture_in_play boolean not null,
    is_homebrew boolean not null,
    is_discordant_stars_mode boolean not null,
    is_absol_mode boolean not null,
    is_franken_mode boolean not null,
    is_alliance_mode boolean not null,
    is_twilight_imperium_global_league boolean not null,
    is_twilight_imperium_global_league_fractured boolean not null,
    twilight_imperium_global_league_rank text,
    player_count integer not null
);

create table game_round_player_stats (
    game_id text not null,
    user_discord_id text not null,
    round integer not null,
    max_army_cost double precision,
    last_seen_army_cost double precision,
    sc_picks text,
    combats_initiated integer,
    tacticals_with_combat integer,
    planets_taken integer,
    planets_stolen integer,
    techs_gained text,
    dice_rolled integer,
    turn_times text,
    primary key (game_id, round, user_discord_id)
);

create table game_round_player_stats_snapshot (
    game_id text not null,
    undo_index integer not null,
    user_discord_id text not null,
    round integer not null,
    max_army_cost double precision,
    last_seen_army_cost double precision,
    sc_picks text,
    combats_initiated integer,
    tacticals_with_combat integer,
    planets_taken integer,
    planets_stolen integer,
    techs_gained text,
    dice_rolled integer,
    turn_times text,
    primary key (game_id, round, undo_index, user_discord_id)
);

create table map_image_data (
    game_name text not null primary key,
    latest_map_image_name text,
    latest_discord_message_id bigint,
    latest_discord_guild_id bigint,
    latest_discord_channel_id bigint
);

create table player (
    id bigint generated by default as identity primary key,
    user_id text not null,
    game_name text not null,
    faction_name text,
    score integer not null,
    total_number_of_turns integer not null,
    total_turn_time bigint not null,
    expected_hits double precision not null,
    actual_hits integer not null,
    is_eliminated boolean not null,
    is_winner boolean not null,
    is_replaced boolean not null,
    constraint uk_player_game_user unique (game_name, user_id)
);

create table player_aggregates (
    user_id text not null primary key,
    completed_games_hash text not null,
    completed_game_count integer not null,
    aggregates_version integer not null,
    aggregates_json text not null,
    computed_at_epoch_ms bigint not null,
    last_error text,
    last_error_at_epoch_ms bigint
);

create table player_map_image_data (
    id bigint generated by default as identity primary key,
    game_name text not null,
    player_id text not null,
    discord_message_id bigint,
    discord_channel_id bigint,
    updated_at timestamp(6),
    constraint uk_player_map_image_data_game_player unique (game_name, player_id)
);

create table title (
    id bigint generated by default as identity primary key,
    game_name text not null,
    user_id text not null,
    title text not null
);

create table standalone_title (
    id bigint generated by default as identity primary key,
    user_id text not null,
    title text not null,
    source text not null,
    constraint uk_standalone_title_user_title_source unique (user_id, title, source)
);

create table tournament_winner (
    id bigint generated by default as identity primary key,
    user_id text,
    user_name text,
    tourney_name text
);

create index idx_combat_observation_started_at on combat_observation (started_at);
create index idx_combat_observation_game_tile_started_at on combat_observation (game_name, tile_position, started_at);
create index idx_combat_candidate_status_started_at on combat_candidate (status, started_at);
create index idx_combat_candidate_promotion_resolved_at on combat_candidate (promotion_status, resolved_at);
create index idx_combat_candidate_game_tile_status on combat_candidate (game_name, tile_position, status);
create index idx_combat_candidate_status_pending_resolution on combat_candidate (status, pending_resolution_started_at);
create index idx_combat_candidate_promoted_at on combat_candidate (promoted_at);
create unique index idx_combat_candidate_event_candidate_sequence on combat_candidate_event (candidate_id, sequence_number);
create index idx_combat_candidate_event_candidate_occurred_at on combat_candidate_event (candidate_id, occurred_at);
create index idx_combat_candidate_event_candidate_type on combat_candidate_event (candidate_id, event_type, actor_faction, round_number);
create index idx_combat_candidate_event_occurred_at on combat_candidate_event (occurred_at);
create index idx_replay_contest_replay_status_due on combat_contest (replay_status, next_replay_at);
create index idx_replay_contest_posted_at on combat_contest (posted_at);
create index idx_replay_contest_public_message on combat_contest (public_message_id);
create index idx_replay_contest_public_thread on combat_contest (public_thread_id);
create index idx_replay_contest_side_bet_posting on combat_contest (replay_status, side_bet_market_posted_at, posted_at);
create index idx_replay_contest_leaderboard_posting on combat_contest (replay_status, leaderboard_posted_at, replay_completed_at);
create index idx_side_bet_contest_user on combat_contest_side_bets (contest_id, discord_user_id);
create index idx_side_bet_resolved on combat_contest_side_bets (resolved_at);
create index idx_hacan_market_compact_decision_contest on combat_replay_hacan_market_compact_decision (contest_id);
create index idx_hacan_subsidy_contest on combat_replay_hacan_subsidy (contest_id);
create index idx_hacan_subsidy_vote_contest on combat_replay_hacan_subsidy_vote (contest_id);
create index idx_hacan_subsidy_vote_user on combat_replay_hacan_subsidy_vote (contest_id, discord_user_id);
create index idx_hacan_trade_convoys_contest on combat_replay_hacan_trade_convoys (contest_id);
create index idx_hacan_trade_convoys_vote_contest on combat_replay_hacan_trade_convoys_vote (contest_id);
create index idx_hacan_trade_convoys_vote_user on combat_replay_hacan_trade_convoys_vote (contest_id, discord_user_id);
create index idx_replay_house_house on combat_replay_house (house);
create index idx_replay_house_ability_use_house on combat_replay_house_ability_use (house);
create index idx_house_ability_vote_candidate_house on combat_replay_house_ability_vote (candidate_id, house);
create index idx_replay_house_opt_out_house on combat_replay_house_opt_out (house);
create index idx_replay_house_score_house on combat_replay_house_score (house);
create index idx_replay_leaderboard_points on combat_replay_leaderboard_entry (total_points);
create index idx_replay_leaderboard_rank on combat_replay_leaderboard_entry (total_points, correct_predictions, prediction_count, discord_user_name);
create index idx_replay_prediction_contest_id on combat_replay_prediction (contest_id);
create index idx_standalone_title_user on standalone_title (user_id);
create index idx_game_ended_at on game (ended_epoch_milliseconds);
create index idx_game_completed_six_player_non_alliance on game (is_completed, is_alliance_mode, player_count, is_twilight_imperium_global_league);
create index idx_game_active_tigl on game (is_twilight_imperium_global_league, ended_epoch_milliseconds);
create index idx_player_user on player (user_id);
create index idx_title_user on title (user_id);
create index idx_title_game on title (game_name);
create index idx_game_round_player_stats_user_game on game_round_player_stats (user_discord_id, game_id);
create index idx_game_round_player_stats_snapshot_game_undo on game_round_player_stats_snapshot (game_id, undo_index);

alter table player add constraint fk_player_user foreign key (user_id) references discord_user (id);
alter table player add constraint fk_player_game foreign key (game_name) references game (game_name);
alter table title add constraint fk_title_user foreign key (user_id) references discord_user (id);
alter table title add constraint fk_title_game foreign key (game_name) references game (game_name);
alter table standalone_title add constraint fk_standalone_title_user foreign key (user_id) references discord_user (id);
