on: workflow_dispatch
name: BotLogCurlTest
jobs:
  build:
    name: BotLogCurlTest
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      with:
        host: ${{ secrets.HOSTINGER_SSH_HOST }}
        username: ${{ secrets.HOSTINGER_SSH_USER }}
        password: ${{ secrets.HOSTINGER_SSH_PASSWORD }}
        port: ${{ secrets.HOSTINGER_SSH_PORT }}
        envs: DISCORD_WEBHOOK_URL
        script: |
          set -eu
          
          timestamp=$(date "+%F %T.%3N")
          curl -X POST -H 'Content-Type: application/json' -d "{\"content\":\"\`$timestamp\`TESTING GITHUB ACTIONS BOTLOG WEBHOOK\"}" $DISCORD_WEBHOOK_URL
          
          echo "DONE!"