on:
  workflow_dispatch:
  # push: # disabled - can be deleted if we're good with the new one
  #   branches: [ "master" ]
name: BuildAndDeploy_Old
concurrency:
  group: "Start Bot"
jobs:
  build:
    name: Build, Test, & Deploy Bot
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      env:
        AWS_KEY: ${{ secrets.IMG_AWS_KEY }}
        AWS_SECRET: ${{ secrets.IMG_AWS_SECRET }}
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        envs: AWS_KEY, AWS_SECRET
        script: |
          echo "Backing up games..."
          cd /root/ti4bot
          ./scheduled_upload.sh
          echo "Pulling changes from GitHub..."
          cd /root/ti4bot/TI4_map_generator_bot
          git pull
          echo "Building docker image..."
          docker version
          docker build --build-arg BOT_KEY=$DISCORD_BOT_KEY --build-arg USER=$DISCORD_USER --build-arg SERVER=$DISCORD_SERVER --build-arg SERVER2=$DISCORD_SERVER2 --build-arg AWS_SECRET=$AWS_SECRET --build-arg AWS_KEY=$AWS_KEY -t tibot .
          echo "Restarting TIBot... giving 300 seconds to shutdown"
          docker stop $(docker ps -q) --time 300
          echo "Backing up games again..."
          cd /root/ti4bot
          ./scheduled_upload.sh
          echo "Starting Container..."
          cd /root
          ./docker_run.sh
          echo "Cleaning up docker stuff..."
          docker rm $(docker ps --filter status=exited -q) || true
          docker rmi -f $(docker images --filter "dangling=true" -q) || true
          echo "DONE!"
